tlaplus/tlaplus

tlatools/src/tlc2/tool/SimulationWorker.java, tlatools/src/tlc2/tool/Simulator.java, tlatools/test-model/simulation/BasicMultiTrace/BasicMultiTrace.tla, tlatools/test-model/simulation/BasicMultiTrace/MCLivenessProp.cfg, tlatools/test/tlc2/tool/simulation/SimulatorTest.java
@lemmy This is a follow up fix for issue #147. It addresses the bug in how we reported liveness violations in the Simulator introduced by [8355920](https://github.com/tlaplus/tlaplus/commit/83559207381b08472f1d1dcf8bb07d08a7f9b089). I updated the logic so that we don't print out a behavior trace twice in case of a liveness exception being thrown by a worker. The liveness checker itself already prints the error message, so the Simulator doesn't need to do so again.
=> Fix reporting of liveness violations in the Simulator

tlatools/src/tla2sany/semantic/LevelNode.java
There seemed to be a naming conflict of the Max definition that required renaming to NumMax but one occurrence had been forgotten.
=> correct Max to NumMax in LevelSpec.tla (contained as comment in LevelNode.java)

tlatools/src/tlc2/TLC.java, tlatools/src/tlc2/output/messages.properties
The GZIP default is defined to be `false` here:
https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/TLCGlobals.java#L163
=> Fix TLC help msg: gzip is off by default

tlatools/customBuild.xml
Addresses issue #363. Adds a new ant target `test-single` so you can run a single unit test class from the command line. For example, you can run
```
ant -Dtest.testcase="pcal.AssignmentToUndeclaredVariableTest" -f customBuild.xml test-single
```
and the output will be:
```
Buildfile: /Users/williamschultz/Desktop/scratchpad/tla-dev/tlatools/customBuild.xml
test-single:
[junit] Running pcal.AssignmentToUndeclaredVariableTest
[junit] Testsuite: pcal.AssignmentToUndeclaredVariableTest
[junit] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 sec
[junit] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 sec
[junit]
[junit] Testcase: macroParam took 0.071 sec
[junit] Testcase: procedure took 0.004 sec
[junit] Testcase: constant took 0.002 sec
[junit] …
```
=> Add ant target that allows for the execution of a single unit test class

tlatools/org.lamport.tlatools/src/tlc2/value/impl/RecordValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/TupleValue.java, tlatools/org.lamport.tlatools/test/tlc2/value/impl/RecordValueTest.java, tlatools/org.lamport.tlatools/test/tlc2/value/impl/TupleValueTest.java
Addresses #456.
I went through the some of the main error messages in TupleValue and RecordValue and tried to make their wording more natural for a reader. I added unit tests for the new error messages. This is how the error messages appear for the test cases I added (each message corresponds to one of the try-catch blocks in the unit test):
**TupleValue**
```
Attempted to access index 2 of tuple
<<"A">>
which is out of bounds.
```
```
Attempted to access tuple at a non integral index: "a"
```
```
Attempted to access tuple at a non integral index: "a"
```
```
Attempted to access tuple with 2 arguments when it expects 1.
```
**RecordValue**
```
Attempted to access nonexistent field 'b' of record
[a |-> "aVal"]
```
```
Attempted to access record by a non-string argument: 0
```
```
Attempted …
```
=> Improve error messages for TupleValue and RecordValue

tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java
This is intended as useful when using SANY as part of shell-based
tooling. The command line flag is introduced to keep it backwards
compatible so that no one breaks.
=> return non-zero error codes from SANY on more errors

CONTRIBUTING.md
The name of the nightly build cask is actually `tla-plus-toolbox-nightly` (https://formulae.brew.sh/cask/tla-plus-toolbox)
=> Add missing hyphen in brew install command

tlatools/org.lamport.tlatools/javacc/tla+.jj
- Fix a typo in `tla+.jj` I found when I was reading through the code
=> Fix typo in tla+.jj

tlatools/org.lamport.tlatools/src/tlc2/TLC.java
instead of module name.
Fixes Github issue #733
[Bug][TLC]
=> TraceExplorationSpec was given main TLA+ file path

tlatools/org.lamport.tlatools/src/tlc2/value/impl/OpRcdValue.java, tlatools/org.lamport.tlatools/test-model/ConstantOperatorConfiguration.cfg, tlatools/org.lamport.tlatools/test-model/ConstantOperatorConfiguration.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/ConstantOperatorConfigurationTest.java
TLC allows configuration files to define partial implementations for constant operators:
```
CONSTANT
F(0) = 1
F(1) = 2
F(2) = 2
```
Because of the way values are initialized, this functionality does not work in current `master`. This PR fixes the problem by defining a custom `initialize()` method for `OpRcdValue` that does not call `fingerPrint()`.
It also adds a regression test to help us preserve this functionality in the future.
=> Fix OpRcdValue initialization

toolbox/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/output/data/TLCVariableValue.java
- Fix a typo in the comment about `TLCFcnElementVariableValue` parsing
* `|->` should be `:>`
=> Fix typo in the comment about TLCFcnElementVariableValue parsing

tlatools/org.lamport.tlatools/src/pcal/PcalSymTab.java, tlatools/org.lamport.tlatools/src/pcal/PcalTranslate.java, tlatools/org.lamport.tlatools/src/tlc2/TraceExplorationSpec.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java
In Java, == compares pointers.  Two `String` instances can have the same characters but live at different locations in memory.  Therefore, strings should always be compared using `a.equals(b)`, not `a == b`.
There are exceptions to the rule: if two strings are "interned" (using `str.intern()`) then they can be safely compared using ==.  All string literals written in the program text are guaranteed to be interned, but strings from user input are not, even if they are equal to a string literal.
Since there are no calls to `.intern()` in the TLA+ source code that I can find, we ought to fix these dangerous comparisons.  However, it is worth noting that these have not caused any (reported) issues so far, and may actually be safe if the strings being compared always point to program string …
=> Fix some instances of string comparison using ==

tlatools/org.lamport.tlatools/src/tlc2/tool/SimulationWorker.java
Resolves #666.
It is a very simple pull request to add action names for simulation mode trace dumps. The added lines are TLA+ comments, which conforms to TLA+ syntax.
Generated trace example:
```
\* <Init line 9, col 9 to line 11, col 17 of module DieHard>
STATE_1 == 
/\ big = 0
/\ small = 0
\* <FillBig line 17, col 12 to line 19, col 21 of module DieHard>
STATE_2 == 
/\ big = 5
/\ small = 0
```
=> Add action names for simulation mode trace dumps

tlatools/org.lamport.tlatools/test/tlc2/tool/CommonTestCase.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github432Test.java, tlatools/org.lamport.tlatools/test/tlc2/tool/distributed/TLCServerTestCase.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/CodePlexBug08EWD840FL2FromCheckpointTest.java
This change slightly simplifies the requirements for running the TLA+ tools tests.  Previously, BASE_DIR (read from the "basedir" system property) required a trailing separator character (e.g. "/" on Linux) to function correctly.
With this change the separator is no longer required, which simplifies running the tests from custom IDEs or other build systems.
In particular, note that Maven sets the "basedir" system property to a normalized path while running tests, meaning that it strips off trailing separators.  This behavior is undocumented and there is no way to override it.
=> Add File.separator after BASE_DIR wherever it is used

tlatools/org.lamport.tlatools/src/tlc2/value/IValue.java
The `Value` classes are very important, but there isn't much documentation about them. I've tried to capture some of the key design points and subtleties on the top-level `IValue` interface.
=> Add a docstring to IValue

CONTRIBUTING.md, DEVELOPING.md
Provides general instructions for building TLC without the Toolbox, using ant on the command line.
Based on the conversation in https://github.com/tlaplus/tlaplus/issues/790, I'm adding to `CONTRIBUTING.md`. I'm keeping the instructions short to address the need of having these commands somewhere. Would a longer version be helpful? Would there be a better file to put it in?
The `ide` instructions mention OpenJDK 14, but this approach was tested and confirmed working with OpenJDK 11. Please let me know if that should be updated to 14.
Directions thanks to @lemmy and @Calvin-L. 
Thank you!
=> Add TLC command-line build instructions

.github/workflows/main.yml, .github/workflows/pr.yml
Requires these PRs be merged:
- https://github.com/tlaplus/Examples/pull/78
- https://github.com/tlaplus/Examples/pull/79
Changes:
1. Emits event during nightly build to trigger tlaplus/examples CI run
2. Runs new tlaplus/examples parse/modelcheck scripts during PR CI run
Ref https://github.com/tlaplus/Examples/issues/77
=> Use updated tlaplus/examples scripts in CI runs

tlatools/org.lamport.tlatools/src/tlc2/tool/EvalControl.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCState.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateFun.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMut.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMutExt.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SymbolNodeValueLookupProvider.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Tool.java, tlatools/org.lamport.tlatools/src/tlc2/util/PartialBoolean.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazySupplierValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazyValue.java, tlatools/org.lamport.tlatools/test-model/Github817.tla, tlatools/org.lamport.tlatools/test/tlc2/debug/TLCDebuggerTestCase.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github817Test.java
This is a small(ish) refactor to the way that `LazyValue` works. It fixes #798, although I want to clarify that I'm not certain this is the right approach. I'm more interested in discussing whether this is a good direction to push. If we decide this is worth doing, I believe it is also compatible with the changes in #799.
**Key idea:**
TLC has had several bugs involving misuse of `LazyValue.val`. Instead of proving every use of that field correct, this change shifts the management of the field to the `LazyValue` class itself. Now callers _must_ specify the behavior and evaluation mode that they are evaluating with when reading the cached value. The cached value is only returned if it was computed using the same behavior and evaluation mode. If it wasn't, it must be recomputed.
**Pros:**
A …
=> LazyValue refactor

tlatools/org.lamport.tlatools/src/pcal/ParseAlgorithm.java, tlatools/org.lamport.tlatools/src/pcal/PcalTLAGen.java, tlatools/org.lamport.tlatools/src/pcal/PcalTranslate.java, tlatools/org.lamport.tlatools/src/pcal/TLAExpr.java, tlatools/org.lamport.tlatools/src/pcal/TLAToken.java, tlatools/org.lamport.tlatools/src/pcal/Test.java, tlatools/org.lamport.tlatools/src/tla2sany/parser/Operator.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LetInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SetOfArgLevelConstraints.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SetOfLevelConstraints.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ThmOrAssumpDefNode.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCState.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMut.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMutExt.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMutSource.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateVec.java, tlatools/org.lamport.tlatools/src/tlc2/util/BigInt.java, tlatools/org.lamport.tlatools/src/tlc2/util/BigSet.java, tlatools/org.lamport.tlatools/src/tlc2/util/LongVec.java, tlatools/org.lamport.tlatools/src/tlc2/util/Vect.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/ValueVec.java, tlatools/org.lamport.tlatools/src/util/Set.java
This commit makes one iota of progress toward the suggestions in #756 by replacing uses of `.clone()` with copy constructors, adding new copy constructors as necessary, and removing `implements Cloneable` from all types that have it.  In my mind, these changes are prerequisites for removing the tools' custom data structures (e.g. `util.Set` and `tlc2.util.Vect`).
The `clone()` method has widely been considered bad practice for many years [1].  Problems include:
- Lack of type safety
- A vague contract
- "Magical" capabilities that can't be replicated in pure Java
Copy constructors are considered a better pattern.
[1]: https://www.artima.com/articles/josh-bloch-on-design
=> Remove uses and overrides of `Object.clone()`

tlatools/org.lamport.tlatools/src/util/FilenameToStream.java, tlatools/org.lamport.tlatools/src/util/SimpleFilenameToStream.java, tlatools/org.lamport.tlatools/test/util/SimpleFilenameToStreamTest.java
This commit also normalizes the whitespace in `FilenameToStream` to four spaces (instead of a mix of tabs and spaces).
=> More comments and tests for `FilenameToStream`

tlatools/org.lamport.tlatools/test/util/SimpleFilenameToStreamTest.java
There were two problems here:
1. A copy-paste bug: I generalized this logic from an older test but did not update the arguments to `resolve`.
2. The final check does not pass when the tests run in a JAR file (as they do for the `test-dist` Ant target).
=> Fix `checkResolveStandardModule` test

.github/workflows/pr.yml
The CI will not pass until these changes are merged: https://github.com/tlaplus/Examples/pull/96
Probably best to re-run the PR CI for these changes after merging the tlaplus/examples changes but before merging these.
=> Use skip parameter for tlaplus/examples CI

tlatools/org.lamport.tlatools/src/tlc2/module/Bags.java, tlatools/org.lamport.tlatools/src/tlc2/module/Sequences.java, tlatools/org.lamport.tlatools/src/tlc2/module/TLC.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Tool.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/Applicable.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/EvaluatingValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/FcnLambdaValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/FcnRcdValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/FunctionValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/MethodValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/OpLambdaValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/OpRcdValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/OpValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/RecordValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/TupleValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/Value.java
This is a refactoring-only change, and therefore very low-priority. But, it fixes a longstanding and (to me) irritating lack of type safety surrounding functions and operators.
----
The `Applicable` interface is widely used, but it is "confused" because functions and operators both implement it, even though those entities have very different capabilities and cannot be interchanged in TLA+.
This commit adds a new `FunctionValue` interface so that TLC's code can distinguish between operators (`OpValue`) and functions.  Despite adding a new interface, the split actually REDUCES the number of non-comment lines of code in TLC.
A few qualitative notes about why I think this is a good refactor:
1. Operator values have to implement `getDomain()` even though they do not have a domain.  Therefore, …
=> Split FunctionValue out of Applicable

tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Tool.java
* https://github.com/tlaplus/CommunityModules/commit/fa56512a37421631ee140e86429e095c532a6904 as minor optimization to mitigate state-space explosion coming from https://github.com/microsoft/CCF/pull/5948#discussion_r1463037681
* DFS mode for trace validation to mitigate state-space explosion coming from https://github.com/microsoft/CCF/pull/5948#discussion_r1463037681
* Marrying DFS and `\cdot`
* Support `-continue` when checking Action Constraints (refinement checking)
* Check invariants during trace validation (proposed in https://github.com/microsoft/CCF/pull/5933)
https://github.com/microsoft/CCF/issues/5057#issuecomment-1910837290
=> Mitigate state-space explosion during trace validation

tlatools/org.lamport.tlatools/src/tla2tex/TeX.java
tla2tex with `-out` option fails if the output file does not exist already.
Fixes Github issue #855
https://github.com/tlaplus/tlaplus/issues/855
[Bug][TeX]
=> tla2tex with `-out` option fails if the output file does not exist already.

tlatools/org.lamport.tlatools/src/tlc2/TLC.java, tlatools/org.lamport.tlatools/test/tlc2/TLCTest.java
When `file=` argument is specified, a `num` argument is required. Fixes #789 
I'm not sure if this is still needed, but I was trying to find a simple bugfix.
=> Fixes issue 789

tlatools/org.lamport.tlatools/src/tlc2/tool/fp/DiskFPSet.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LSBDiskFPSet.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/MSBDiskFPSet.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/OffHeapDiskFPSet.java, tlatools/org.lamport.tlatools/src/tlc2/util/BufferedRandomAccessFile.java, tlatools/org.lamport.tlatools/test/tlc2/util/BufferedRandomAccessFileTest.java
Discovered while investigating #835.
----
This commit fixes a latent cache inconsistency bug in `OffHeapDiskFPSet`.  There are no symptoms today, but problems will arise if we change almost anything in the implementation of `BufferedRandomAccessFile` or `DiskFPSet`.
Most implementations of `DiskFPSet.Flusher` write directly to the output file through the provided output file descriptor `outRAF`.  But, the concurrent flushing algorithm in `OffHeapDiskFPSet` actually writes to the output file through newly-allocated file descriptors.  As a result, any buffered data in `outRAF` will be incorrect following a flush because the on-disk data was modified through different file descriptors.
Today there are some subtleties in the implementation of `BufferedRandomAccessFile` that prevent this from …
=> In `OffHeapDiskFPSet`, invalidate buffered data after concurrent flush

tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/AbstractDiskGraph.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/ILiveCheck.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck1.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/NoOpLiveCheck.java, tlatools/org.lamport.tlatools/test/tlc2/tool/CommonTestCase.java
Discovered while working on #835.
I am not in love with this fix, and I am open to other ideas. But, it seemed to be the most straightforward way to fix the problem.
----
This commit fixes a latent issue in the test suite.
`CommonTestCase.assertNodeAndPtrSizes` makes assertions about the on-disk state of some files that are internal to `AbstractDiskGraph`. These checks are useful, but today they only pass because of two brittle implementation details:
- `BufferedRandomAccessFile` flushes writes to disk when seeking backward in the file.
- Backward seeks are very common.
The checks will break if we optimize `BufferedRandomAccessFile` to flush less often or if we change how `AbstractDiskGraph` reads/writes its internal files.
To make the tests less brittle, this commit introduces a new …
=> Flush writes to disk before asserting facts about the disk files

tlatools/org.lamport.tlatools/.classpath, tlatools/org.lamport.tlatools/test/tla2sany/OperatorPrecedenceTests.java
These tests exhaustively check all pairwise interactions of infix, prefix, and postfix operator symbols. 10,000 parse inputs are checked in approximately one second. These tests found the following two bugs:
- #892
- #893
They serve as a solid basis for near-future work changing the SANY initialization process to not use a JavaCC-generated "Configuration" grammar to parse a string to load all the operator details into itself, which will also facilitate some work on #891.
There is no risk to approving these changes as it is only unit test code.
=> Test operator precedence & associativity parsing

tlatools/org.lamport.tlatools/src/tlc2/TLCGlobals.java, tlatools/org.lamport.tlatools/src/tlc2/tool/AbstractChecker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/ModelChecker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/SimulationWorker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/coverage/CostModelNode.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/ActionItemList.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Tool.java
Action and variable coverage will not be reported on the command-line as like TLC's other coverage information, but exclusively as part of `TLCGet("spec")`.
[Feature][TLC]
=> Support enabling action and variable coverage independently of more expensive formula and value coverage.

tlatools/org.lamport.tlatools/src/tla2sany/configuration/ConfigConstants.java, tlatools/org.lamport.tlatools/src/tla2sany/configuration/Configuration.java, tlatools/org.lamport.tlatools/src/tla2sany/parser/Operator.java, tlatools/org.lamport.tlatools/src/tla2sany/parser/Operators.java, tlatools/org.lamport.tlatools/test/tla2sany/ParseCorpusTest.java
`Operators.DefinitionTable` is one of three separate tables that must be initialized before SANY will parse anything (the others are `Context.initialContext` and `BuiltInLevel.LevelData`). Prior to these changes, `Operators.DefinitionTable` was initialized by calling `Configuration.Load` which used the JavaCC-generated parser in `tla2sany/configuration` to parse a string in `tla2sany/configuration/ConfigConstants.java` containing precedence & associativity info for all the TLA+ operator symbols, then loading those symbols into the table. This changes that operation into a simple loop in a `static` block over a static array of `Operator` objects.
1. Partially (but not completely) removes the necessity of calling `Configuration.load` before using SANY, in line with the goal of #891 
2. …
=> Statically initialize operators table

tlatools/org.lamport.tlatools/src/tlc2/tool/ModelChecker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/ModelConfig.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Spec.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java
This hook can be set up using the (provisional) `_PERIODIC` keyword within the configuration file.
[Feature][TLC]
=> Add TLC hook to periodically evaluate a constant-level expression.

.github/workflows/pr.yml
These steps used to execute sequentially and now execute in parallel. This uses three CI VMs instead of one, but now the PR CI completes in 15 minutes instead of 30 minutes. The jobs are as follows:
1. tlatools unit tests (this takes the longest, ~15 minutes)
2. eclipse toolbox maven build/test (~5 minutes)
3. tlaplus/examples integration tests (~10 minutes)
I also upgraded some of the github action versions so they stop printing out node version warnings.
=> Parallelize PR CI workflow

.github/scripts/parse-unit-test-output.py, .github/workflows/pr.yml, tlatools/org.lamport.tlatools/customBuild.xml, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/ModelCheckerTestCase.java, tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/SimulationWorkerTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/SimulatorTest.java
This was actually easier than expected (edit: it was not easier than expected). Somehow I missed that the JUnit task has a `threads` parameter. I guess this is a newer addition which is why not a lot of documentation mentions it. Now the unit test target will run with number of threads equal to available cores on the machine. Decent improvement, unit tests finish in less than 10 minutes now which puts them below the time of the tlaplus/examples integration tests! There were a few small changes I had to make to some tests to ensure they don't interfere with each other with operations on the `states` metadir.
I also added a useful python script to run during the CI after the tests; it:
- Prints the total number of tests and total number of failed tests
- Prints out any tests that were run …
=> Parallelize unit tests

tlatools/org.lamport.tlatools/test/tlc2/tool/fp/OffHeapDiskFPSetTest.java
Related to #835, but not a complete fix.
----
In Java 21 the various `RandomAccessFile` read methods like `readLong()` are now implemented using bulk array reads, not single-byte reads.  Therefore, `DummyRandomAccessFile` needs to implement those methods if it is to function as intended.
=> Fix `OffHeapDiskFPSetTest.testWriteIndex()` on Java 21

.github/scripts/parse-unit-test-output.py, .github/workflows/pr.yml, tlatools/org.lamport.tlatools/customBuild.xml, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/ModelCheckerTestCase.java
The threads parameter limits parallelization so users can reserve part of their workstation for other tasks as the tests are running, although if that task is running TLC then it might interfere with the tests.
=> Fix unit test error reporting and support `-Dthreads=N` parameter

tlatools/org.lamport.tlatools/src/tlc2/tool/impl/DebugTool.java
debugger.
Related to git commit c2713def38aa1d3255a6c2fe2aa037253e00e361
Have DebugTool implement INotInModelFunctor.
[Bug][TLC]
=> 'constrained' states not added to e.g. dot output if TLC runs under TLA+

.github/workflows/pr.yml, tlatools/org.lamport.tlatools/src/pcal/PcalBuiltInSymbols.java, tlatools/org.lamport.tlatools/src/pcal/PcalCharReader.java, tlatools/org.lamport.tlatools/src/pcal/Tokenize.java, tlatools/org.lamport.tlatools/src/pcal/trans.java, tlatools/org.lamport.tlatools/src/tla2tex/Misc.java
This PR does not add Unicode support to PlusCal. It simply ensures that PlusCal code reads & writes files encoding with UTF-8 (done by default across Java's `nio` API) and uses codepoints (represented as `int`s in Java) instead of `char`s when tokenizing the input.
Prior to these changes running `pcal.trans` on a file with Unicode symbols on Windows would result in garbled output.
Added a step to the PR CI which runs `pcal.trans` against all PlusCal files in the tlaplus/examples repo.
=> Make pcal.trans unicode-safe

.github/workflows/main.yml, .github/workflows/perf.yml, .github/workflows/pr.yml
Github actions has stopped serving the specific version of Java we use (11.0.3) which breaks our CI. To fix this we just use a non-specific version of Java 11 for everything.
=> Use Java 11 but not specific version in CI

tlatools/org.lamport.tlatools/customBuild.xml, tlatools/org.lamport.tlatools/pom.xml
=> Target Java 11 in all builds

.github/ISSUE_TEMPLATE/---bug-report.md
Having created some reports to TLA+ it always feels weird to me to see how in the issue template the "Expected behavior" goes *before* "Steps to reproduce".
Take [this report](https://github.com/tlaplus/tlaplus/issues/929) for example: when I read from top to bottom, I see paragraph "Expected behavior" starting with `You succeed` — and I think to myself "Mhm? Succeed in what?". This is confusing. That's because paragraphs "Expected/Actual" describe whatever happens from the "Steps" *(whereas "Description" paragraph usually provides some general information: usecase, why, when; basically creates context for "minimal steps" further below)*. But since "Steps" are located after the "expected result", this breaks reader's flow and creates confusion.
So, how about moving "Steps to reproduce" to …
=> ISSUE_TEMPLATE: moving "Steps to reproduce" to go before Expected/Actual

tlatools/org.lamport.tlatools/customBuild.xml, tlatools/org.lamport.tlatools/javacc/tla+.jj, tlatools/org.lamport.tlatools/src/tla2sany/explorer/Explorer.java, tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParser.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LevelConstants.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SetOfArgLevelConstraints.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SetOfLevelConstraints.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Subst.java, tlatools/org.lamport.tlatools/src/tla2sany/xml/SymbolContext.java, tlatools/org.lamport.tlatools/src/tlc2/module/TransitiveClosure.java, tlatools/org.lamport.tlatools/src/tlc2/tool/distributed/TLCApp.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/AbstractDiskGraph.java
These are generally trivial. I blanket-silenced the `sun.misc.Unsafe` warnings using a `javac` parameter. I would like to add `-Werror` to prevent further warnings from being introduced but am blocked on #921
=> Fixed miscellaneous javac compiler warnings

tlatools/org.lamport.tlatools/customBuild.xml, tlatools/org.lamport.tlatools/src/pcal/PCalUnrecoverableErrorRuntimeException.java, tlatools/org.lamport.tlatools/src/pcal/PcalTranslate.java, tlatools/org.lamport.tlatools/src/tla2sany/configuration/ASCII_CharStream.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ParseUnit.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/SpecObj.java, tlatools/org.lamport.tlatools/src/tla2sany/utilities/Assert.java, tlatools/org.lamport.tlatools/src/tlc2/model/TypedSet.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/FPSetConfiguration.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/MemFPSet1.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/ModelConfig.java, tlatools/org.lamport.tlatools/src/tlc2/util/BigSet.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/SymmetryTableauLiveCheckTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/other/CheckFP.java, tlatools/org.lamport.tlatools/test/tlc2/tool/other/CurrentDir.java, tlatools/org.lamport.tlatools/test/tlc2/tool/other/FileClassLoader.java
This extracts the un-contentious changes from #931 to fix a bunch of trivial warnings about deprecated functions that were introduced by the migration to Java 11.
It adds `-Werror` to the `compile-test` target at least.
=> Fix java 11 warnings

tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/SymmetryTableauLiveCheckTest.java
version of Easymock than what TLAToolbox.target defines.
Refactoring: https://github.com/tlaplus/tlaplus/commit/4d60a40d599ef4c5fcbef573e96af125a0661028
[Build][TLC][Test]
=> Fix compiler error introduced by recent refactoring that assumes a newer

.github/workflows/pr.yml, tlatools/org.lamport.tlatools/src/pcal/ParseAlgorithm.java, tlatools/org.lamport.tlatools/src/pcal/PcalBuiltInSymbols.java, tlatools/org.lamport.tlatools/src/pcal/PcalTranslate.java, tlatools/org.lamport.tlatools/src/pcal/TLAExpr.java, tlatools/org.lamport.tlatools/src/pcal/Tokenize.java
These changes build on top of https://github.com/tlaplus/tlaplus/pull/909. They make the PlusCal translator correctly parse Unicode input. However, it will still always output generated TLA+ code in ASCII.
For testing, all PlusCal modules in the tlaplus/examples repo are converted to Unicode then translated.
Closes #928
=> Support Unicode in `pcal.trans`

general/docs/current-tools.md, tlatools/org.lamport.tlatools/src/tlc2/TLC.java, toolbox/org.lamport.tla.toolbox.doc/html/model/tlc-options-page.html
Persist the learning from issue #883. Diameter is non-deterministic when the BFS is run with multiple workers.
=> Update documentation about non-deterministic diameter with multiple workers

tlatools/org.lamport.tlatools/src/tlc2/TLC.java
Hello, I find that the description of dump option of tla2tools.jar is not consistent with https://lamport.azurewebsites.net/tla/current-tools.pdf. Therefore, I update it following the description in the pdf.
=> <doc>: update description of dump option.

tlatools/org.lamport.tlatools/customBuild.xml
I wanted to start contributing some tests, but it was hard to understand which lines are not covered. I know there is a test-dist command, but for some reason Intellij was not able to load it and the generated report is also empty. In this PR, I'm adding a new command for ant `jacoco-report` that generates the HTML report. Using `ant -f customBuild.xml test-dist jacoco-report` will run the tests with 8 threads and generate the html report in `target/site/index.html`. If you're curious, the reported coverage is at 60% at the moment (according to this output, not sure how precise it is).
=> Generate test coverage report in html

tlatools/org.lamport.tlatools/test/tlc2/tool/fp/MultiFPSetTest.java
This should improve the reliability of this test, fixing exceptions like
Table violates invariants prior to eviction: [...]
thrown by `OffHeapDiskFPSet.checkInput`.
The tests now pass even with the very pessimistic patch below in place; previously they did not always pass because the internal `LongArray` object(s) could have arbitrary contents.  The call to `init` is responsible for zeroing out any internal `LongArray` objects.
Test patch (not checked in for performance reasons):
diff --git a/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java b/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java
index 85e720456..e90023632 100644
--- a/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java
+++ b/tlatools/org.lamport.tlatools/src/tlc2/tool/fp/LongArray.java
@@ …
=> Add missing `init` calls in `MultiFPSetTest`

tlatools/org.lamport.tlatools/src/tlc2/tool/impl/WorkerValue.java, tlatools/org.lamport.tlatools/test-model/Github866.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/Github866Test.java
Fixes Github issue #866
https://github.com/tlaplus/tlaplus/issues/866
[Bug][TLC]
=> Reset random number generator before evaluating constants per worker.

tlatools/org.lamport.tlatools/test/tlc2/tool/CommonTestCase.java
Git commit ad454838ad3eaa296aad212e5e1d480b450ead37 unintentionally broke test execution in Eclipse. This commit, however, resolves the issue, so tests no longer require manually setting the basedir in Eclipse
[Tests][TLC]
=> All JUnit tests fail when executed from within Eclipse unless the basedir is explicitly set.

DEVELOPING.md
Small issue I noticed when trying to follow the instructions on Linux.
=> Fix Eclipse native hook refresh setting instructions on Linux

tlatools/org.lamport.tlatools/src/util/SimpleFilenameToStream.java
If a given `path` exists on the classpath in multiple places, `class.getResource(path)` will return an arbitrary one of them.  This behavior creates a potential problem for `SimpleFilenameToStream` when running the TLA+ tests:
- Main classes and test classes are placed in separate folders, and both folders are on the classpath.
- The path "tla2sany/" exists in both locations, since there are some test classes in the `tla2sany` package.
As a result, `SimpleFilenameToStream` may decide that the installation base path is actually "test-classes/tla2sany", which does not contain a "StandardModules" folder.
This is not a problem in most cases, since in practice `getResource` returns the _first_ place it found the requested path, and the main classes go on the classpath first.  But that behavior …
=> Locate the the "StandardModules" folder more reliably

DEVELOPING.md
Closes #983.
I synthesized the short set of initial recommendations from a few different sources:
- Sun's original "Java Code Conventions" document (https://www.oracle.com/technetwork/java/codeconventions-150003.pdf)
- Google's Java style guide (https://google.github.io/styleguide/javaguide.html)
- Wikipedia's description of the "One True Brace Style" (https://en.wikipedia.org/wiki/Indentation_style#One_True_Brace)
- OpenJDK's draft Java Style Guidelines (https://cr.openjdk.org/~alundblad/styleguide/index-v6.html)
- The behavior of a few popular Java formatters, including Palantir (https://github.com/palantir/palantir-java-format) and Spotless (https://github.com/diffplug/spotless)
=> Add a short style guide to DEVELOPING.md

DEVELOPING.md
Ran into some very weird Ant compilation failures in the CLI and found they were caused by the Eclipse "Refresh using native hooks or polling" setting; added a note about this interference to the developing docs.
=> Add note about Eclipse interference with Ant CLI build

tlatools/org.lamport.tlatools/src/tlc2/REPL.java
Quitting out of the REPL with Ctrl+D or piping input to the REPL always results in
org.jline.reader.EndOfFileException
at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:697)
at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:512)
at tlc2.REPL.runREPL(REPL.java:191)
at tlc2.REPL.main(REPL.java:236)
This is quite distracting; end-of-file is a normal condition and there is no reason to see its stacktrace.
This commit silences the noisy output.  It also adds a warning if some partially-entered input would be ignored because of the end-of-file (which should be a rare condition).
=> Silence noisy `EndOfFileException`

tlatools/org.lamport.tlatools/src/tlc2/value/impl/BoolValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/EvaluatingValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/FcnLambdaValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/FcnRcdValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/IntValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/IntervalValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/LazyValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/MethodValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/ModelValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/OpLambdaValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/OpRcdValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/RecordValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetCapValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetCupValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetDiffValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetEnumValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetOfFcnsValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetOfRcdsValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetOfTuplesValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SetPredValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/StringValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/SubsetValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/TupleValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/UndefValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/UnionValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/UserValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/Value.java, tlatools/org.lamport.tlatools/test/tlc2/value/impl/EnumerableValueTest.java
This method is not used by the Toolbox, the Community Modules, or TLC itself.
The `assignable()` method creates problems for Java module overrides because it is package-private.  A package-private method cannot be overridden by another class in a different package, meaning that module overrides cannot create their own `Value` implementations.
----
@lemmy I ran into this while trying to write a new overridden operator for the Community Modules. Making the method `public` would also fix the problem, but this seemed cleaner since it isn't used anywhere.
=> Remove `Value.assignable()`

tlatools/org.lamport.tlatools/src/pcal/Validator.java
I have hopes that this will address #1005, although I cannot actually test that it does on my Windows install locally.
=> Fix PlusCal Unicode handling on Windows

tlatools/org.lamport.tlatools/customBuild.xml
Another minor thing to come out of my Windows bug-bashing jaunt. My understanding of how line endings work with git is if a file has entirely line endings of a certain type (all LF or all CRLF), git does not actually store its line endings internally & it is checked out with different line endings depending on what OS you are using. All the generated JavaCC files have uniform line endings, so if you clone the repo on Windows the files will all have CRLF line endings (and LF if cloned on linux/macOS). Thus if you run the Ant JavaCC generate target it will force-convert them all to LF and so cause a spurious local diff when nothing really changed. This removes the LF conversion step and so the files will just be output as whatever is the OS default.
I recall this force-LF step was …
=> Don't enforce LF line endings on JavaCC-generated code

tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java
This will add a log line:
```
Computed 1 initial states...
Finished computing initial states: 1 distinct state generated at 2024-09-28 00:26:25.
```
It's not super informative, but it's helpful for the ux of the vscode extension. Without it, users need to wait about a minute to get another log line before seeing something on the table:
This adds the initial line:
I think it's helpful to know that something is happening behind the scenes.
=> Print a log message whenever simulator has finished to compute initial state

general/docs/current-tools.md, tlatools/org.lamport.tlatools/src/tlc2/TLC.java
Subcommand causes TLC to include states in the dot file that are excluded from the model via a state or action constraint.
Feature introduced in git commit 24479f74c8a02fbe2f83981ca6210e2f7fa7799f
https://github.com/tlaplus/tlaplus/commit/24479f74c8a02fbe2f83981ca6210e2f7fa7799f
[Doc]
=> Add documentation for `constrained` sub-command

tlatools/org.lamport.tlatools/.settings/org.eclipse.core.resources.prefs
This solved Leslie Lamport's issues developing on Windows in https://github.com/tlaplus/tlaplus/pull/911#discussion_r1789191547
=> Add Eclipse project setting file enforcing UTF-8 usage

tlatools/org.lamport.tlatools/src/tlc2/TLC.java, tlatools/org.lamport.tlatools/test/tlc2/TLCTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/simulation/LiveCheckSimulationTest2.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/simulation/LiveCheckSimulationTest2a.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/simulation/SimulationTest2.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/simulation/SimulationTest2PostCondition.java, tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/Github602Test.java, tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/NQSpecTest.java
Another easy fix to advance the goal of https://github.com/tlaplus/tlaplus/issues/891 and simplify testing.
Similar to #1033
=> Convert TLC.traceNum to a non-static class variable

tlatools/org.lamport.tlatools/src/tlc2/tool/ModelChecker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java, tlatools/org.lamport.tlatools/test-model/CodePlexBug08/EWD840MC1.tla, tlatools/org.lamport.tlatools/test-model/CodePlexBug08/MCa.tla, tlatools/org.lamport.tlatools/test-model/Test3.tla, tlatools/org.lamport.tlatools/test-model/symmetry/OneBitMutex/OneBitMutexNoSymmetryMC.tla
POSTCONDITION is evaluated twice with different values for TLCExt!Counterexample when TLC detects a liveness violation.
[TLC][Bug]
=> POSTCONDITION is evaluated twice with different values for TLCExt!Counterexample when TLC detects a liveness violation.

tlatools/org.lamport.tlatools/javacc/tla+.html, tlatools/org.lamport.tlatools/javacc/tla+.jj, tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParser.java
I used Eclipse's nice test coverage highlighting to identify code in the JavaCC-generated parser which is not exercised, then confirmed that no reference to any of these functions exists. Removing them increases test coverage of `TLAplusParser.java` from 69.9% to 76.8%, in addition to making the grammar easier to understand. All told about 700 lines are removed.
There were some ASCII page break characters I also removed. I also took the liberty of replacing the exactly three tab characters in the entire file with spaces.
Finally, I also automatically regenerate the `javacc/tla+.html` file in the Ant `generate` task now.
This will cause merge conflicts with #1015 and #1019 so I'll resolve them in whichever gets merged last.
=> Removed dead code from JavaCC-generated parser

tlatools/org.lamport.tlatools/src/tla2sany/xml/XMLExporter.java
Closes #1053 
This issue occurred because the http://tla.msr-inria.inria.fr/tlaps/sany.xsd link was broken. Thankfully the .xsd XML schema file lives in the tla2sany/xml directory so can be fetched as a local resource instead.
=> SANY XML exporter: use local schema file

tlatools/org.lamport.tlatools/src/tla2sany/xml/XMLExporter.java
These quick changes pretty-print the output XML by default, but add the `-t` CLI flag for terse output.
I split this out of #1055 because that was getting a bit large.
=> SANY XML: pretty-print by default and add terse CLI option

tlatools/org.lamport.tlatools/src/tlc2/module/TLCGetSet.java, tlatools/org.lamport.tlatools/test-model/Github866.tla, tlatools/org.lamport.tlatools/test-model/TLCGetLevel.cfg, tlatools/org.lamport.tlatools/test-model/TLCGetLevel.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/Github866Test.java, tlatools/org.lamport.tlatools/test/tlc2/tool/TLCGetLevelTest.java
```
Attempted to apply the operator overridden by the Java method
public static tlc2.value.impl.Value
tlc2.module.TLCGetSet.TLCGetEval(tlc2.tool.impl.Tool,tla2sany.semantic.ExprOrOpArgNode[],tlc2.util.Context,tlc2.tool.TLCState,tlc2.tool.TLCState,int,tlc2.tool.coverage.CostModel),
but it produced the following error:
class tlc2.tool.Action cannot be cast to class
tla2sany.semantic.OpDefNode (tlc2.tool.Action and
tla2sany.semantic.OpDefNode are in unnamed module of loader 'app')
```
Follow-up from db98efba8a9000d7f2afa13fb66d796d4a36dbaf
[Bug][TLC]
=> ClassCastException when evaluating TLCGet("spec") with coverage enabled.

.github/workflows/pr.yml
Docs: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
Learned about this from https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions
=> Cancel PR CI workflow runs when newer changes are pushed

tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck1.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/Liveness.java
Fixes Github issue #1065
https://github.com/tlaplus/tlaplus/issues/1065
[Bug][TLC]
=> Checking liveness properties in simulation mode creates a scalability bottleneck due to unnecessary sharing of ILiveCheck instances.

tlatools/org.lamport.tlatools/src/tla2sany/xml/XMLExporter.java, tlatools/org.lamport.tlatools/test/tla2sany/xml/TestXMLExporterHelpText.java
It's difficult to add this in a way that helps in all cases without totally rewriting the very flawed parse logic but this is the minimal diff. Now outputs the following help text:
```
NAME
tla2sany.xml.XMLExporter - Emit SANY's parse tree as XML - Version 2.2 created 08 July 2020
SYNOPSIS
tla2sany.xml.XMLExporter [-Iot] [-help] FILE
DESCRIPTION
Given a TLA+ file, parse that file with SANY then translate the module's semantic parse tree to XML, including all the modules depended on. The XML is printed to stdout and its output format is given by an XML Schema file (.xsd) found at https://proofs.tlapl.us/doc/web/sany.xsd.
OPTIONS
-I
Include; use given directory path to resolve module dependencies.
-help
Print this usage information.
-o
Offline mode; skip XML schema validation step.
-t …
```
=> SANY XML: added CLI help text

tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java
Fixes #947 
- Show usage when no argument is provided.
- Show error and refer to `-help` when no file argument is provided.
- Slight rewording of existing options.
- Added mandatory `FILE...` argument.
- Added explanation for commands that can be used in the Semantic Graph Explorer.
This results in:
```
NAME
SANY - provides parsing, semantic analysis, and level-checking for a TLA+ spec - Version 2.2 created 08 July 2020
SYNOPSIS
SANY [-dls] [-error-codes] FILE...
DESCRIPTION
SANY is a parser and syntax checker for TLA+ specifications.
It catches parsing errors and some "semantic" errors such as
priming an expression containing primed variables.
OPTIONS
-d
Opens the semantic graph explorer prompt. The prompt accepts the following commands:
'cst' Prints out the concrete syntax tree.
'dot' …
```
=> SANY commandline enhancements

tlatools/org.lamport.tlatools/src/tlc2/TLC.java, tlatools/org.lamport.tlatools/src/tlc2/debug/TLCStackFrame.java, tlatools/org.lamport.tlatools/src/tlc2/tool/ITool.java, tlatools/org.lamport.tlatools/src/tlc2/tool/ModelChecker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCState.java, tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMutExt.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/WorkerValue.java, tlatools/org.lamport.tlatools/src/tlc2/util/SetOfStates.java
Previously, the debugger could only run with a single worker (`-workers 1`), limiting its usefulness for large models. This commit introduces support for running the debugger with multiple workers (`-workers N`).
The debugger attaches to one worker, while the other workers continue without being directly debugged. This setup reduces debugging overhead, such as the creation of stack frames, on the non-debugged workers.
=> [Provisional] Support running the TLA+ debugger with multiple workers.

tlatools/org.lamport.tlatools/src/tlc2/tool/SimulationWorker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/SingleThreadedSimulator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/StateVec.java, tlatools/org.lamport.tlatools/test/tlc2/tool/SimulatorTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/SimulationWorkerTest.java
To simplify the counterexample, simulation removes finite stuttering steps (1f9f3cb59854937547a24d59e057cec02d476d5f), reducing traces like `<<a, a, a, b, b, c>>` to `<<a, b, c>>`. This PR ensures that e.g. `TLCGet("level")` correctly evaluates in an ALIAS or POSTCONDITION to 1, 2, and 3 for the three respective states. Previously, it incorrectly evaluated to something like 1, 4, and 6.  This is done by [refactoring the code to consistently append](https://github.com/tlaplus/tlaplus/pull/1080/commits/584d80050a53289b3f4c28001619620923c2af6c) the final `TLCState` to the `stateTrace`, and [iterating over the trace and resetting the predecessor](https://github.com/tlaplus/tlaplus/pull/1080/files#diff-bd04d84aca8a7e75ede389a9ce669443a04f037ea49425d2cf3e88371c6da98dR793-R796) for each state in …
=> Correct the predecessors and level of *all* states after dropping  *finite* stuttering steps.

tlatools/org.lamport.tlatools/src/tlc2/tool/ModelChecker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java, tlatools/org.lamport.tlatools/test-model/Github1087.cfg, tlatools/org.lamport.tlatools/test-model/Github602.tla, tlatools/org.lamport.tlatools/test-model/TLCGetAll.tla, tlatools/org.lamport.tlatools/test-model/ViewMap.tla, tlatools/org.lamport.tlatools/test-model/cdot/ChainedCdots.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/ChainedCdotsTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1087Test.java, tlatools/org.lamport.tlatools/test/tlc2/tool/TLCGetAllTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/ViewMapTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/OneBitMutexNoSymmetryTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/simulation/Github602Test.java
NullPointerException when last state of the trace is *not* in the model.
If the final state of a counterexample is excluded from the model because state- or action-constraints evaluate to false, it is not written to the trace file.  This omission causes a NullPointerException when attempting to read the final state from the trace file during counterexample reconstruction.  To address this issue, the final state is now explicitly appended to the counterexample to ensure completeness and avoid runtime errors.
[Bug][TLC]
=> NullPointerException when last state of the trace is *not* in the model.

tlatools/org.lamport.tlatools/src/tla2sany/explorer/ExplorerVisitor.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpApplNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SemanticNode.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Tool.java, tlatools/org.lamport.tlatools/src/tlc2/util/Vect.java, tlatools/org.lamport.tlatools/test-model/CyclicRedefine.tla, tlatools/org.lamport.tlatools/test-model/CyclicRedefineInit.cfg, tlatools/org.lamport.tlatools/test-model/CyclicRedefineInstance.cfg, tlatools/org.lamport.tlatools/test-model/CyclicRedefineInstance.tla, tlatools/org.lamport.tlatools/test-model/CyclicRedefineNext.cfg, tlatools/org.lamport.tlatools/test-model/CyclicRedefineOp.cfg, tlatools/org.lamport.tlatools/test-model/CyclicRedefineSubAction.cfg, tlatools/org.lamport.tlatools/test-model/CyclicRedefineVars.cfg, tlatools/org.lamport.tlatools/test-model/CyclicRedefineVars.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/CyclicRedefineInitTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/CyclicRedefineInstanceTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/CyclicRedefineNextTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/CyclicRedefineOpTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/CyclicRedefineSubActionTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/CyclicRedefineVarsTest.java
A cyclic redefinition RF is a formula that is defined from another formula F while also re-defining F:
```tla
---- MODULE ModuleWithF ----
F == /\ A
/\ B
/\ C
====
---- MODULE Derived -----
EXTENDS ModuleWithF
RF == /\ F
/\ D
====
Config file:
CONSTANT F <- RF
```
Supported:
- Initial predicate
- Next-state relation
- 0-arity and higher-arity sub-actions provided the parameters are constant level
- Invariants
- Ordinary operators
=> Support cyclic redefinitions if -Dtlc2.tool.impl.SpecProcessor.allowCyclicRedefinitions=true is given

tlatools/org.lamport.tlatools/src/tlc2/tool/impl/ModelConfig.java
This pull request introduces a new Java system property, `-Dnosymmetry`, which allows users to ignore the SYMMETRY declaration in .cfg files during model checking. This feature is designed to simplify the use of a single .cfg file for both safety and liveness property checks, without requiring manual modifications to the file.
Usage :
After building the custom `tla2tools.jar` containing the enhancement:
```bash
java -Dtlc2.tool.impl.ModelConfig.nosymmetry=true -cp tla2tools.jar tlc2.TLC MySpec.tla
```
This will run the spec as if no `SYMMETRY` field was specified in `.cfg` file.
The `.cfg` files without `SYMMETRY` will not change their behavior.
To run the spec as usual (i.e. with `SYMMETRY` if there are) you can type as usual:
```bash
java -cp tla2tools.jar tlc2.TLC MySpec.tla
```
or …
=> Add java property '-Dtlc2.tool.impl.ModelConfig.nosymmetry'

tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpApplNode.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestLevelChecking.java
There are a number of places in `OpApplNode` where level-checking errors are logged but the level-checking process itself is not marked as failed. I fixed this and added positive & negative tests for all of these cases.
Originally this testing was motivated by noticing that this code was branching on ASCII versions of operator names like `[]` but that turned out not to be a problem.
=> Level-checking: fix false acceptances in OpApplNode

tlatools/org.lamport.tlatools/src/tla2sany/README
Fix typo in README
In this PR, I have corrected a typo in the project's README file, changing "t0" to "to". 
Although the change is minor, I hope it helps improve the accuracy and readability of the documentation. 
Thank you to the maintainers for their hard work!
=> Fix typo: change 't0' to 'to' in README

tlatools/org.lamport.tlatools/src/tlc2/debug/TLCStateStackFrame.java, tlatools/org.lamport.tlatools/src/tlc2/tool/SimulationWorker.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/StateVec.java, tlatools/org.lamport.tlatools/test/tlc2/debug/TLCDebuggerTestCase.java
ArrayIndexOutOfBoundsException in TLA+ debugger during simulation if simulator eliminated finite stuttering from current trace.
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 82 out of
bounds for length 82
at tlc2.tool.StateVec.elementAt(StateVec.java:78)
at tlc2.tool.SimulationWorker.getTraceInfo(SimulationWorker.java:811)
at tlc2.tool.Simulator.getTraceInfo(Simulator.java:816)
at tlc2.debug.TLCStateStackFrame.lambda$getVariables$2(TLCStateStackFrame.java:163)
at tlc2.tool.impl.DebugTool.eval(DebugTool.java:686)
at tlc2.debug.TLCStateStackFrame.getVariables(TLCStateStackFrame.java:141)
at tlc2.debug.TLCDebugger.variables(TLCDebugger.java:547)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
... 13 more
```
Related to …
=> ArrayIndexOutOfBoundsException in TLA+ debugger during simulation if simulator eliminated finite stuttering from current trace.

tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/APSubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/AnyDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/AssumeNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/AssumeProveNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/AtNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/DecimalNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/DefStepNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/FormalParamNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/InstanceNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LabelNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LeafProofNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LetInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LevelNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ModuleNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/NewSymbNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/NonLeafProofNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/NumeralNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpApplNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpArgNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDeclNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/StringNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Subst.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/TheoremNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ThmOrAssumpDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/UseOrHideNode.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestLevelChecking.java
This was suggested by @lemmy in #1099 and I think it's a good idea so splitting it off into its own PR.
These changes do something a bit more advanced, which is add an `Errors` log parameter to enable users of this API to split logging of the level-checking process off from the semantic checking process.
Before these changes, all semantic and level-checking error logging were co-mingled in an annoying static global log in `SemanticNode#errors`. This has to be initialized with a static call to `SemanticNode#setError` before running semantic or level-checking analysis. While these changes do not get rid of this static log, it reduces the number of times it is used in the codebase from 49 to 32. Hopefully future changes can chip away at this and get it down to zero, thus reducing the number …
=> Add LevelNode#levelCheck API for public consumption

tlatools/org.lamport.tlatools/src/tla2sany/drivers/InitException.java, tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/SpecObj.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Context.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java, tlatools/org.lamport.tlatools/src/tlc2/tool/CheckImplFile.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java, tlatools/org.lamport.tlatools/test-model/tla2sany/semantic/TestMergeContextError.tla, tlatools/org.lamport.tlatools/test-model/tla2sany/semantic/TestMergeContextWarning.tla, tlatools/org.lamport.tlatools/test/tla2sany/drivers/Bug156TEStackOverflowTest.java, tlatools/org.lamport.tlatools/test/tla2sany/drivers/Github429Test.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestMergeContextError.java, toolbox/org.lamport.tla.toolbox/src/org/lamport/tla/toolbox/spec/parser/ModuleParserLauncher.java
PR #1067 made me realize that SANY has retained its error reporting machinery for initialization failures when those failures are no longer possible due to #1012. So I removed this machinery.
This did result in one functional change: when extending a spec, the new spec's symbols are read into the symbol context of the current spec (see `mergeExtendContext`). If any symbol conflicts occurred these were recorded in the initialization error log path (code comments reveal this behavior was an object of some confusion as these errors were getting "lost" so special code was necessary to report these errors). These errors will now be reported through the well-trodden semantic error log path.
=> SANY: Removed init error logging since it's static now

tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java, tlatools/org.lamport.tlatools/src/tla2sany/explorer/Explorer.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/APSubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/DefStepNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ExternalModuleTable.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/FormalParamNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/InstanceNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LeafProofNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LevelNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ModuleNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/NonLeafProofNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpApplNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDeclNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SymbolNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/TheoremNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ThmOrAssumpDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/UseOrHideNode.java, tlatools/org.lamport.tlatools/src/tlc2/tool/Specs.java, tlatools/org.lamport.tlatools/test/tlc2/tool/coverage/OpApplNodeWrapperTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/TBParTest.java, tlatools/org.lamport.tlatools/test/tlc2/util/ContextTest.java
Reduce usage of static SemanticNode.errors field
Some additional places of use remain but this is a good incremental effort. Reduced usage count from 32 to 7.
This was all fairly mechanical (adding `Errors` parameters to methods) except for two places:
1. When constructing the SANY `Explorer` instance which is used to print out the SANY parse tree from the command line, provide `spec.getSemanticErrors()` which is the same `Errors` logging instance as the `SemanticNode.errors` field whose usage is being replaced
2.  In `tlatools/org.lamport.tlatools/src/tlc2/tool/Specs.java`, which is the only non-SANY part of the codebase calling into a `tla2sany.semantic` class constructor requiring an `Errors` instance (`SubstInNode`), I provide a new blank `Errors` instance; this means if an error is …
=> SANY: Remove most static error logging usage

tlatools/org.lamport.tlatools/src/tlc2/tool/fp/OffHeapDiskFPSet.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/OpenAddressing.ConcurrentFlusher.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/fp/OffHeapDiskFPSetTest.java
This PR addresses the issue in https://github.com/tlaplus/tlaplus/issues/1112 where the `DiskFPSet.mergeNewEntries` method enters an infinite loop when it encounters the `fp = value` (see the TLA+ counterexample below). While this PR doesn’t resolve the root cause of duplicate fingerprints, it will aid us in understanding the frequency of such occurrences.
```tla
TLC2 Version 2.20 of Day Month 20?? (rev: https://github.com/tlaplus/tlaplus/commit/66d04b7817b76939c8504a4fb3f0bada22a1bf6e)
Running breadth-first search Model-Checking with fp 88 and seed -3725596570278802435 with 1 worker on 10 cores with 7282MB heap and 64MB offheap memory [pid: 87860] (Mac OS X 15.2 aarch64, Homebrew 23.0.1 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file …
```
=> Warning: DiskFPSet.mergeNewEntries: xxx is already on disk with hangup following

tlatools/org.lamport.tlatools/src/tlc2/tool/fp/DiskFPSet.java, tlatools/org.lamport.tlatools/test/tlc2/tool/fp/AbstractHeapBasedDiskFPSetTest.java
Do not abort recover but continue recovery if it encounters a duplicate fingerprint and `-Dtlc2.tool.fp.DiskFPSet.error2warning=true` is given.
Part of Github issue #1113
https://github.com/tlaplus/tlaplus/issues/1113
[Bug][TLC]
=> Do not abort recover but continue recovery if it encounters a duplicate fingerprint and `-Dtlc2.tool.fp.DiskFPSet.error2warning=true` is given.

.github/FUNDING.yml
It was still pointing to the MSR website.
=> Changed funding link to TLA⁺ Foundation website

tlatools/org.lamport.tlatools/src/tlc2/output/EC.java, tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/fp/OffHeapDiskFPSet.java, tlatools/org.lamport.tlatools/test/tlc2/tool/fp/LongArraysTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/fp/OffHeapIndexerTest.java
Warning: DiskFPSet.mergeNewEntries: xxx is already on disk with hangup following. 
Use double precision when calculating `tblScalingFactor` to avoid rounding issues in `Indexer#getIdx`. These rounding issues can lead to critical errors, such as the largest fingerprints being incorrectly mapped to lower indices instead of the highest index.  This problem occurs intermittently for specific ranges of positions within the interval `(0, Integer.MAX_VALUE)`.
Part of Github issue #1112
https://github.com/tlaplus/tlaplus/issues/1112
[Bug][TLC]
=> Warning: DiskFPSet.mergeNewEntries: xxx is already on disk with hangup following.

tlatools/org.lamport.tlatools/src/util/SimpleFilenameToStream.java
Fixes a bug in commit eaeb041d (#1116).  On Windows, path URLs have a form like
file:/C:/path
Taking `URL.getPath()` gives back
/C:/path
which is not a legal Windows path.  However, there is built-in functionality for converting URLs to paths, which I should have used from the beginning. The built-in functionality correctly recovers the path
C:\path
=> Fix path resolution on Windows

tlatools/org.lamport.tlatools/test/util/SyntaxCorpusRunner.java
Minor change now that I've learned about this feature. Previously, skipped tests would simply be marked as succeeding.
=> Change syntax corpus runner to use JUnit.Assume

tlatools/org.lamport.tlatools/test/tla2sany/parser/CanonicalOperatorTests.java, tlatools/org.lamport.tlatools/test/tla2sany/parser/OperatorAssociativityTests.java, tlatools/org.lamport.tlatools/test/tla2sany/parser/OperatorPrecedenceTests.java
Nicely separate test cases using JUnit runner logic. Previously this was run in one test in a gigantic for-loop but now we split it into different cases using JUnit 4's parameterized class functionality. This does increase the runtime a bit (now runs on the order of 1-2 seconds) but should be worth it for debugging failures. We can now see how many test cases are generated - around 13,000, and these tests don't include the Unicode operator variants!
Previously there were three separate tests that ran in the same class but due to how JUnit class parameterization works I needed to separate these out into their own classes.
[Refactor][Test][SANY]
=> Parameterize operator precedence tests with JUnit

tlatools/org.lamport.tlatools/src/tla2sany/semantic/Errors.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestErrors.java
The motivation for these changes are to facilitate development & testing of https://github.com/tlaplus/rfcs/issues/15. In general, it is also nice for users to have programmatic access to error messages (locations and such) instead of them being encoded in a string.
These changes do three things and are broken into a series of logical commits:
1. (Before any changes) Write regression tests against the `Error` class API to ensure these changes do not break anything
2. Refactor the class to use a standard Java `List<>` instead of our custom `Vector` class
3. Change the `Errors` class to store `ErrorDetails` objects instead of string-serialized messages; this class is serialized to a string (in the same format as before) upon request.
The intention here is that this makes it very easy to …
=> Refactor Errors log class to keep error deserialized internally

tlatools/org.lamport.tlatools/src/tlc2/debug/AttachingDebugger.java, tlatools/org.lamport.tlatools/src/tlc2/debug/TLCDebugger.java, tlatools/org.lamport.tlatools/src/tlc2/debug/TLCStackFrame.java
As described in #1143, `StoppedEvent`'s `reason` field is now missing while it is mandatory, which causes some clients to fail to work with TLC debugger.
=> Fill mandatory reason field to comply with the protocol (fixes #1143)

tlatools/org.lamport.tlatools/src/tlc2/value/impl/FcnLambdaValue.java, tlatools/org.lamport.tlatools/test-model/Github1145.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1145Test.java
Fixes #1145.
The `toTuple()` method does not take `this.excepts` into account.  As a result, TLC might mis-evaluate certain expressions involving functions.
To fix the problem, this commit replaces manual calls to `tool.eval` with calls to `select(Value)`, which correctly handles excepts.
=> Handle excepts in FcnLambdaValue.toTuple()

tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/queue/DiskByteArrayQueue.java, tlatools/org.lamport.tlatools/src/tlc2/util/ObjectPoolStack.java, tlatools/org.lamport.tlatools/src/tlc2/util/StatePoolReader.java
Part of Github issue #1154
https://github.com/tlaplus/tlaplus/issues/1154
[Bug][TLC]
=> Include name of poolFile in error message when de-serialization fails.

tlatools/org.lamport.tlatools/src/tlc2/debug/TLCDebugger.java, tlatools/org.lamport.tlatools/src/tlc2/debug/TLCSourceBreakpoint.java, tlatools/org.lamport.tlatools/src/tlc2/debug/TLCStackFrame.java
Previously (see git commit https://github.com/tlaplus/tlaplus/commit/f849bf1b8f85960c0c0ca2cae1034a1feeb20b52), only hit count conditions were supported.  The hit count condition can now be expressed as `TLCGet("level") >= C`, where C is the desired hit count.  If the root module does not (transitively) extend the TLC module, the expression becomes `LET T == INSTANCE TLC IN T!TLCGet("level") >= C`.
Related: https://github.com/tlaplus/tlaplus/commit/afd53e936b41b88791a8dfe0b9ce59987dec203e
Enabled by Github PR https://github.com/tlaplus/tlaplus/pull/1099 "Debugger: Add support for on demand breakpoint expressions"
https://github.com/tlaplus/tlaplus/pull/1099
=> Support expressions as filters for unsatisfied breakpoints.

.github/workflows/pr.yml
The `--enable_assertions` parameter was added in https://github.com/tlaplus/Examples/pull/157 and https://github.com/tlaplus/Examples/pull/161 as suggested by @lemmy. The flag runs tla2tools.jar-based tools with the java `-enableassertions` flag.
Skip checking MCDistributedReplicatedLog since it fails with assertions due to #1045. PR #1111 can remove this skip as a form of proof that it fixes the issue.
Minor additional change: check SpecifyingSystems example modules in CI; these were previously skipped due to Unicode restrictions that no longer apply.
=> CI: Add `--enable_assertions` flag to tlaplus/examples scripts

DEVELOPING.md
=> Docs: JDK 11 is required to build toolbox

tlatools/org.lamport.tlatools/src/tlc2/output/EC.java, tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java
`Warning: The formula Inv is a state-level formula, but it was used as a PROPERTY (or PROPERTIES), where a temporal formula is typically expected. State-level formulas used as PROPERTY or PROPERTIES are only checked in the initial state. To verify that the formula Inv holds in all states of every behavior, use INVARIANT Inv instead. Alternatively, applying the "always" temporal operator (□) to the state-level formula Inv changes it into a temporal formula, asserting that Inv holds in all states of every behavior.`
[Feature][TLC]
=> Raise a warning if a state-level formula is used as a PROPERTY.

tlatools/org.lamport.tlatools/src/tlc2/output/EC.java, tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java
`Warning: Temporal properties (PROPERTY or PROPERTIES) are being verified without a behavior specification (SPECIFICATION). Only INIT and NEXT have been provided. This is likely to result in (trivial) counterexamples showing infinite stuttering following the initial state. It is recommended to use SPECIFICATION Spec, with Spec asserting a suitable fairness constraint (compare Chapter 8, page 87ff of Specifying Systems at https://lamport.azurewebsites.net/tla/book.html).`
[Feature][TLC]
=> Raise a warning if checking temporal properties without a behavior spec.

tlatools/org.lamport.tlatools/customBuild.xml
With #1176 merged, it is now possible to build a native version of SANY that starts up much faster.
If you have installed GraalVM, you should have the executable `native-image` on your $PATH and you can run
ant -f customBuild.xml dist-sany-graal-native
to build a native `./sany` executable.
The new build command is currently undocumented and subject to change. In particular, I am not certain I have included all the neccessary resource files for everything SANY can do.  I have only tested that `./sany` correctly loads one large well-formed TLA+ spec.
=> Add ant target for building SANY as a Graal native image

tlatools/org.lamport.tlatools/src/tlc2/module/Integers.java, tlatools/org.lamport.tlatools/src/tlc2/module/Naturals.java, tlatools/org.lamport.tlatools/src/tlc2/module/Sequences.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/Tool.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/UserObj.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/UserValue.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/Value.java
```
TLC encountered a non-enumerable quantifier bound
Seq({1, 2}).
line 49, col 17 to line 49, col 26 of module DieHard
```
```
TLC encountered the non-enumerable quantifier bound
Seq({1, 2})
line 49, col 17 to line 49, col 26 of module DieHard
In TLA+, Seq(S) represents the set of all finite sequences whose
elements come from the set S. Even when S is a finite set, the number of
possible sequences in Seq(S) is unbounded because sequences can have any
finite length (e.g., length 0, 1, 2, and so on). As a result, TLC cannot
evaluate expressions that universally (\A) or existentially (\E)
quantify over Seq({1, 2}), because this would require checking an
infinite number of cases. Note that for a finite set of sequences s, TLC
handles s \subseteq Seq(S).
```
```
TLC encountered the …
```
=> Improve error messages when TLC encounters an non-enumerable value.

tlatools/org.lamport.tlatools/src/tla2sany/semantic/ErrorCode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/error_corpus/W4802_Pre_Test.tla
Addresses Github issue #1184
https://github.com/tlaplus/tlaplus/issues/1184
[Feature][TLC]
```
The field name "SomeField" in the record constructor is identical to the existing definition or declaration
named SomeField, located at line 5, col 1 to line 6, col 4 of module RiverCrossingFlashlight.
The field in the record will not take the value of the SomeField definition or declaration.
In TLA+, field names in records are strings, regardless of any similarly named declarations or definitions.
Therefore, DOMAIN [SomeField |-> ...] = {"SomeField"} holds true.
```
=> Raise warning when symbol appears in Records.

docs/module-coverage-statistics.md, tlatools/org.lamport.tlatools/src/tlc2/output/EC.java, tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/coverage/CostModelCreator.java
Report distinct variable values observed in TLC coverage statistics.
Activated by passing `-Dtlc2.TLCGlobals.coverage=2` in addition to
`-coverage someInterval`.
These statistics show the number of unique values each variable takes
during model checking. An unusually high number of values for a
particular variable may suggest that the model is not properly
constrained, potentially leading to state space explosion during
exhaustive analysis.
Note I: The underlying data structure used to estimate these counts is
probabilistic (specifically, HyperLogLog) to minimize its memory
overhead. As a
result, the reported counts may include some margin of error. Moreover,
it introduce contention among the workers and will, thus, negatively
impact performance and scalability.
Note II: The …
=> Add variable coverage to `-coverage` output

tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ParseUnit.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/SpecObj.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Errors.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDefNode.java, tlatools/org.lamport.tlatools/test/tla2sany/api/SANYFrontend.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/SemanticErrorCorpusTests.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestErrors.java, toolbox/org.lamport.tla.toolbox/src/org/lamport/tla/toolbox/spec/parser/ModuleParserLauncher.java
These changes support #1186
Remove unnecessary delineation to support adding more levels
Before these changes, there were separate methods in the Errors class for adding "aborts" vs. adding "errors". The only actual difference between these was that adding an abort also threw an exception if the caller set a boolean parameter to true. Every caller to Errors::addAbort() set this parameter to true. So, the Errors::addAbort() method has been unified with the Errors::addError() method. The Errors::addError() method has also been modified so it returns an AbortException that can be optionally thrown by the caller. Internally, aborts and errors go into the same list.
Why make these changes? We want to support additional logging levels for better control of SANY output. Within a schema of …
=> SANY error logging: aborts are now errors with exceptions

tlatools/org.lamport.tlatools/src/tlc2/output/EC.java, tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java, tlatools/org.lamport.tlatools/test-model/ConstLevelInvariant.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/ConstLevelInvariantTest.java
```
Warning: The invariant ConstLevelInvariant is a constant-level formula (i.e., it contains no variables, primes, or temporal operators) and evaluates to TRUE. To assert constant-level formulas in your spec, use ASSUME ConstInv, or to give the assumption a name such as YourAssumption, use ASSUME YourAssumption == ConstInv.
```
[Feature][TLC]
=> Do not ignore silently but raise warning if an invariant is a *constant-level* formula.

DEVELOPING.md
Supersedes #1206; while running `nix-shell --pure` it was discovered that toolbox maven builds will fail if git is not available on the path. Thus document that git is required to build the toolbox in DEVELOPING.md.
=> Docs: git is a dependency of the toolbox build

tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ParseUnit.java, tlatools/org.lamport.tlatools/test/tla2sany/output/RecordedSanyOutput.java, tlatools/org.lamport.tlatools/test/tla2sany/parser/ParseErrorTests.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/SemanticCorpusTests.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/SemanticErrorCorpusTests.java, tlatools/org.lamport.tlatools/test/tlc2/output/SpecTraceExpressionWriterTest.java
As part of PR #1209, SANY output was centralized into a single logging class. These changes extended to the TLAplusParser class, which was given an additional constructor accepting a SanyOutput parameter. Unfortunately the existing constructors were auto-generated by JavaCC so could not be removed, and the code constructing TLAplusParser in ParseUnit.java was neglected to be updated to use the new constructor accepting the SanyOutput parameter. By default the calls to SanyOutput in TLAplusParser were sent to a SilentSanyOutput instance, and so this had the effect that all detailed parse error messages occuring at the syntax level and below were silenced. The parse failure itself was recorded, but the specific reason for the failure was not output.
These changes update ParseUnit to use the …
=> SANY bugfix: syntax parser errors were incorrectly silenced

tlatools/org.lamport.tlatools/src/tlc2/output/EC.java, tlatools/org.lamport.tlatools/src/tlc2/output/MP.java, tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/Liveness.java
Add debugging capabilities to TLC's liveness checking functionality by providing two Java system property-based debugging aids: statistics printing and tableau graph visualization.
Adds the system property `-Dtlc2.tool.liveness.Liveness.debug=true` to enable printing of liveness checking complexity statistics. Adds the system property `-Dtlc2.tool.liveness.Liveness.tableauExportPath=/out/put/path.dot` to export tableau graphs in GraphViz DOT format.
[Feature][TLC]
=> Add debugging aids to (i) print statistics about the complexity of liveness checking, and (ii) visualize the tableau graph with GraphViz.

tlatools/org.lamport.tlatools/src/tla2sany/semantic/ErrorCode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Errors.java, tlatools/org.lamport.tlatools/test/tla2sany/api/SANYFrontend.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/SemanticCorpusTests.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/SemanticErrorCorpusTests.java, tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestErrors.java
Also unified error reporting to single method
In commit be86598, error messages were tagged with a standardized error code. This code also contains an associated error level. Thus, in these changes the error reporting methods addError() and addWarning() are merged into a single method addMessage(), since the error level is already encoded in the standardized error code. The existing methods were tagged as deprecated. Some test code was updated to use the new method.
[SANY][Refactor]
=> SANY: created unified errors.addMessage() error reporting method

DEVELOPING.md
Addresses #1198.
It was not my intention to be prescriptive here.  The default Eclipse settings use tabs.
Until we reach consensus on what style (if any) to standardize on, I don't think there's a reason to have a fine-grained rule in this slot. The number one rule above still stands:
> 1. Modifications should copy the style of nearby code rather than change it.
=> Relax recommendation for tabs over spaces

tlatools/org.lamport.tlatools/javacc/tla+.jj, tlatools/org.lamport.tlatools/src/tla2sany/explorer/Explorer.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ModulePointer.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ModuleRelatives.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ParseUnit.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/ParseUnitRelatives.java, tlatools/org.lamport.tlatools/src/tla2sany/modanalyzer/SpecObj.java, tlatools/org.lamport.tlatools/src/tla2sany/parser/OperatorStack.java, tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParser.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/APSubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Context.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ExternalModuleTable.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LabelNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/LetInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ModuleNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/NonLeafProofNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/OpDefNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SubstInNode.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/SymbolTable.java, tlatools/org.lamport.tlatools/src/tla2sany/semantic/ThmOrAssumpDefNode.java
Many usages of the internal SANY Vector class do not use a generic type parameter. This means there is a lot of unnecessary casting and confusion about what any given Vector instance contains. These changes add type parameters to all Vector usages, greatly improving code understandability. Unnecessary casts are also removed when found, and the `final` annotation was added to many uses.
While this is a large diff to review it is all checked by the type system so is safe.
[SANY][Refactor]
=> SANY: Add type parameters to Vector usage

pom.xml, toolbox/org.lamport.tla.toolbox.feature.standalone/feature.xml, toolbox/org.lamport.tla.toolbox.product.product/TLAToolbox.target, toolbox/org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product
A dependency of CloudTLC is causing notarization to fail on macOS. Since CloudTLC is unlikely to still be in use by many users, it is removed from the Toolbox.
```
-> % xcrun notarytool log 22b35405-c20f-4fef-8952-7468376c632b --apple-id *** --team-id ***
{
"logFormatVersion": 1,
"jobId": "22b35405-c20f-4fef-8952-7468376c632b",
"status": "Invalid",
"statusSummary": "Archive contains critical validation errors",
"statusCode": 4000,
"archiveFilename": "TLAToolbox-1.8.0-macosx.cocoa.x86_64.zip",
"uploadDate": "2025-09-06T00:01:16.192Z",
"sha256": "5007b1c25df54e6f04f2ba12e3d381158aa83bd5756b4d633fbb3066982afac4",
"ticketContents": null,
"issues": [
{
"severity": "error",
"code": null,
"path": "TLAToolbox-1.8.0-macosx.cocoa.x86_64.zip/TLA+ …
```
=> Remove CloudTLC from Toolbox.
