tlaplus/tlaplus

README.md
=> Add basic landing page for project.

tlatools/src/pcal/Region.java, tlatools/src/tla2sany/configuration/ASCII_CharStream.java, tlatools/src/tlc2/util/ByteUtils.java, tlatools/src/util/MailSender.java
Using ErrorProne (https://errorprone.info) to catch issues when building tlatools.
=> Fixing issues caught by ErrorProne.

tlatools/src/tlc2/module/AnySet.java, tlatools/src/tlc2/module/Bags.java, tlatools/src/tlc2/module/FiniteSets.java, tlatools/src/tlc2/module/Integers.java, tlatools/src/tlc2/module/Naturals.java, tlatools/src/tlc2/module/Sequences.java, tlatools/src/tlc2/module/Strings.java, tlatools/src/tlc2/module/TransitiveClosure.java
1. Added @Override.
2. Removed unnecessary casts
2. Added the final modifier to a constant field
=> Sonarqube, corrections according to recommendations

tlatools/org.lamport.tlatools/src/tla2sany/semantic/Generator.java, tlatools/org.lamport.tlatools/test-model/sany/Github723.tla, tlatools/org.lamport.tlatools/test/tla2sany/Github723Test.java
=> Check arity for implicit substitutions

general/docs/contributions.md
(Finally) following up on #756, here is a bit of writing about documentation and code quality improvements we're looking for.
Did I miss any? Or include any that we actually want to discourage?
I considered including one about improving the build system as well (see e.g. the separation bullet in #778). However, improving/rewriting the tools build system seems like a complex job to me, and I wasn't sure exactly what I could put in the wishlist that would be useful.
=> Add documentation and code quality improvements to the wishlist

tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/Liveness.java, tlatools/org.lamport.tlatools/test-model/Github819.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/Github819Test.java
empty set in liveness conditions.
https://github.com/tlaplus/tlaplus/issues/819
[Bug][TLC]
=> Unexpected temporal formula error when universally quantifying over an

.github/workflows/pr.yml
The PR workflow will fail until these changes are merged: https://github.com/tlaplus/Examples/pull/141
=> Fix CI in response to breaking changes in tlaplus/examples repo

.github/workflows/pr.yml
=> Use correct keyword.

.github/workflows/main.yml, .github/workflows/pr.yml
=> Having fun with pr.yml

tlatools/org.lamport.tlatools/test/tlc2/TraceExpressionSpecTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/liveness/ModelCheckerTestCase.java
=> Output unit test TE specs to unique directories

tlatools/org.lamport.tlatools/src/pcal/PcalParams.java
Follow-up of Github PR #976
https://github.com/tlaplus/tlaplus/pull/976
[Feature][Pcal]
=> Increment translator's version number.

DEVELOPING.md
CC @juliaferraioli
Ref #778
Ref #935
Ref #936
=> Expand DEVELOPING.md

tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java, tlatools/org.lamport.tlatools/test/tlc2/tool/SimulatorTest.java
=> Fixes unreachable branch in Simulator#printBehavior

README.md
=> Added note about sonatype maven packages to top-level README

tlatools/org.lamport.tlatools/src/tlc2/tool/Simulator.java
Related to Github issue #1023
https://github.com/tlaplus/tlaplus/issues/1023
[Feature][TLC]
=> Evaluate `_PERIODIC` in simulation mode.

tlatools/org.lamport.tlatools/src/tlc2/module/TLCGetSet.java, tlatools/org.lamport.tlatools/src/tlc2/value/impl/RecordValue.java, tlatools/org.lamport.tlatools/test-model/Github807.tla
=> Include CONSTRAINT and ACTION_CONSTRAINT in TLCGet("spec").

tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck1.java
`Tool#getState(fp, predecessor)` may fail if `Next` includes the evaluation of `RandomElement` or any other random operator. However, the simulator does not need to recreate states from fingerprints because it retains the current sequence of states.
[Bug][TLC]
=> TLC throws an EvalException when reconstructing a counterexample if the next-state relation involves TLC!RandomElement.

tlatools/org.lamport.tlatools/src/tlc2/TLC.java
Here's an easy fix to advance the goal of #891
=> Convert MODEL_PART_OF_JAR static variable to class variable

tlatools/org.lamport.tlatools/src/tlc2/tool/TLCStateMutExt.java, tlatools/org.lamport.tlatools/src/tlc2/tool/impl/DebugTool.java, tlatools/org.lamport.tlatools/test-model/Echo/MCEcho.cfg, tlatools/org.lamport.tlatools/test-model/Echo/MCEcho.tla, tlatools/org.lamport.tlatools/test/tlc2/debug/EchoDebuggerTest.java
Addresses Github issue #1052
https://github.com/tlaplus/tlaplus/issues/1052
[Feature][TLC][Debugger]
=> Cannot debug TLC VIEW with TLA+ Debugger.

tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck1.java
Part of Github issue #485
https://github.com/tlaplus/tlaplus/issues/485
[Feature][TLC]
=> Evaluate the ALIAS expression on counterexamples generated by liveness checking while running in simulation mode.

tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java, tlatools/org.lamport.tlatools/test-model/DotConstrained.cfg, tlatools/org.lamport.tlatools/test-model/Github602.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/DotConstrainedTest.java
The exception was a java.lang.ArrayIndexOutOfBoundsException : Index 0 out of bounds for length 0
[Bug][TLC]
=> The exception was a java.lang.ArrayIndexOutOfBoundsException : Index 0 out of bounds for length 0

tlatools/org.lamport.tlatools/test/tla2sany/semantic/TestLevelChecking.java
As suggested by @Calvin-L this gives much nicer JUnit output & control for unit tests of this type.
=> Use JUnit parameterization for level-checking tests

tlatools/org.lamport.tlatools/src/tlc2/tool/impl/SpecProcessor.java, tlatools/org.lamport.tlatools/test-model/gh1134/Base.tla, tlatools/org.lamport.tlatools/test-model/gh1134/MC.tla, tlatools/org.lamport.tlatools/test-model/gh1134/MCa.cfg, tlatools/org.lamport.tlatools/test-model/gh1134/MCb.cfg, tlatools/org.lamport.tlatools/test-model/gh1134/MCc.cfg, tlatools/org.lamport.tlatools/test-model/gh1134/MCd.cfg, tlatools/org.lamport.tlatools/test-model/gh1134/MCe.cfg, tlatools/org.lamport.tlatools/test-model/gh1134/MCf.cfg, tlatools/org.lamport.tlatools/test-model/gh1134/MultiUser.tla, tlatools/org.lamport.tlatools/test-model/gh1134/SingleUser.tla, tlatools/org.lamport.tlatools/test-model/gh1134/UserStateMachine.tla, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1134aTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1134bTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1134cTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1134dTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1134eTest.java, tlatools/org.lamport.tlatools/test/tlc2/tool/Github1134fTest.java
Fixes Github issue #1134
https://github.com/tlaplus/tlaplus/issues/1134
[Bug][TLC]
=> TLC calls operator with wrong value.

tlatools/org.lamport.tlatools/test/tla2sany/parser/OperatorAssociativityTests.java, tlatools/org.lamport.tlatools/test/tla2sany/parser/OperatorPrecedenceTests.java
=> Fix compile error due to concurrent PRs

tlatools/org.lamport.tlatools/src/pcal/trans.java, tlatools/org.lamport.tlatools/test/pcal/PcalParamsTest.java
=> Add validation for `labelRoot` command line option

docs/seq-unenumerable.md, tlatools/org.lamport.tlatools/src/tlc2/module/Sequences.java
=> Add extended documentation how to handle `\E s \in Seq(S):...` and `\A s \in Seq(S):...`

.github/workflows/pr.yml
Reflect changes in https://github.com/tlaplus/Examples/pull/180
The tlaplus/examples PR CI will be broken until these changes are merged.
[CI]
=> CI: use new parameters for tlaplus/examples CI scripts

.github/workflows/pr.yml, .gitignore, pom.xml, toolbox/org.lamport.tla.toolbox.feature.standalone/feature.xml, toolbox/org.lamport.tla.toolbox.p2repository/category.xml, toolbox/org.lamport.tla.toolbox.product.product/TLAToolbox.target, toolbox/org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product, toolbox/org.lamport.tla.toolbox.product.product/pom.xml, toolbox/org.lamport.tla.toolbox.product.standalone/src/org/lamport/tla/toolbox/ApplicationWorkbenchWindowAdvisor.java, toolbox/org.lamport.tla.toolbox/plugin.xml
https://github.com/tlaplus/tlaplus/issues/1241
=> Upgrade to newer Eclipse SDK due to Apple Notarization issues
